### PR TITLE
Update MiniGrafx.h

### PR DESCRIPTION
**Pull request by mattncsu**
Adds invert function to swap black and white colors.

### CODE REVIEW

**Comment by squix78** [comment]
Hi Matt. 

Thanks so much for your contribution! I have two questions about your code:
1) How does the invert method work for more than two colors and with palettes? The library and all methods should support these modes as well.
2) What does the drawString90 do? I would expect that it draws a string rotated by 90 degrees (or even better a multiple of 90 degrees). But it looks as if draws rotated by 350 degrees? If it was just rotating 90 degrees then I guess we could avoid the cos and sin operations since this can be calculated with a simple matrix (I guess)

What do you think?

**Comment by mattncsu** [comment]
I'm working with an e-paper display so my code for invert did not consider
a multicolor display. The idea is that it simply swapped black with white
and vice versa.  If the palette is fixed then I suppose you could match up
color pairs but it might get tricky if the palette is user definable (I
haven't played with color lcds at all so I'm not sure how that works)

drawString90 started as a function to draw the string rotated 90 degrees
but I found and adapted a code example that would rotate a bitmap by an
aritrary angle so I decided to go that way instead.  I need to go back and
rename the function something different or even better, pass angle as a
parameter to drawString--I haven't implemented actually passing the angle
which is why 350 degrees was hardcoded in.  It's a real hack job right now
just to get something down on paper. I read about using lookup tables to
avoid having to do the sin/cos calculations. The performance didn't seem
too bad on my ESP8266, probably would be bad on a less powerful arduino
board.

**Comment by mattncsu** [comment]
I'm probably misusing the pull request feature since the code isn't ready for primetime.. This is my first time actually interacting on github besides just downloading code to my local machine.

**Comment by mattncsu** [comment]
Dropped the drawString90 and related functions and integrated the rotation into the setPixel function.  Only thing we need to do is figure out how to center the rotated string on the original x,y coordinates. I think it is rotating about 0,0 or 0,y. Any ideas or suggestions?

**Comment by squix78** [comment]
Hi Matt. I'm sorry that I ignored your pull request for such a long time, just too many things going on. Is there a technical reason why we should close this pull request?

**Comment by mattncsu** [comment]
I never developed the rotate function further and superseded the "invert" function with "colorSwap" (see pull #16) that works on multicolor displays.

**Pull request closed without merging**
